
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('attendees').del()
    .then(function () {
      // Inserts seed entries
      return knex('attendees').insert([
        {event_id:10,user_id:15},
        {event_id:33,user_id:43},
        {event_id:39,user_id:15},
        {event_id:8,user_id:32},
        {event_id:37,user_id:15},
        {event_id:3,user_id:50},
        {event_id:26,user_id:31},
        {event_id:13,user_id:23},
        {event_id:34,user_id:6},
        {event_id:22,user_id:30},
        {event_id:4,user_id:30},
        {event_id:26,user_id:3},
        {event_id:20,user_id:14},
        {event_id:28,user_id:29},
        {event_id:33,user_id:29},
        {event_id:17,user_id:44},
        {event_id:33,user_id:9},
        {event_id:45,user_id:22},
        {event_id:34,user_id:28},
        {event_id:25,user_id:28},
        {event_id:31,user_id:47},
        {event_id:34,user_id:16},
        {event_id:49,user_id:19},
        {event_id:39,user_id:27},
        {event_id:29,user_id:16},
        {event_id:2,user_id:6},
        {event_id:41,user_id:32},
        {event_id:3,user_id:14},
        {event_id:35,user_id:41},
        {event_id:31,user_id:6},
        {event_id:11,user_id:28},
        {event_id:32,user_id:40},
        {event_id:43,user_id:5},
        {event_id:32,user_id:12},
        {event_id:40,user_id:19},
        {event_id:6,user_id:41},
        {event_id:37,user_id:29},
        {event_id:47,user_id:29},
        {event_id:5,user_id:50},
        {event_id:15,user_id:40},
        {event_id:49,user_id:42},
        {event_id:20,user_id:23},
        {event_id:22,user_id:46},
        {event_id:10,user_id:30},
        {event_id:33,user_id:42},
        {event_id:48,user_id:30},
        {event_id:32,user_id:18},
        {event_id:4,user_id:6},
        {event_id:9,user_id:11},
        {event_id:27,user_id:4}
      ]);
    });
};
