
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('comments').del()
    .then(function () {
      // Inserts seed entries
      return knex('comments').insert([
        {event_id:28,user_id:5,comment:"Green vine snake"},
        {event_id:16,user_id:18,comment:"Civet, common palm"},
        {event_id:10,user_id:22,comment:"Black kite"},
        {event_id:46,user_id:30,comment:"Currasow (unidentified)"},
        {event_id:10,user_id:15,comment:"Mongoose, small indian"},
        {event_id:10,user_id:3,comment:"Steenbok"},
        {event_id:49,user_id:37,comment:"Common green iguana"},
        {event_id:12,user_id:47,comment:"Toucan, red-billed"},
        {event_id:30,user_id:10,comment:"North American river otter"},
        {event_id:32,user_id:29,comment:"Blue and yellow macaw"},
        {event_id:27,user_id:36,comment:"Arctic ground squirrel"},
        {event_id:45,user_id:10,comment:"Baboon, yellow"},
        {event_id:14,user_id:31,comment:"Crow, american"},
        {event_id:47,user_id:11,comment:"Rattlesnake, eastern diamondback"},
        {event_id:41,user_id:45,comment:"Red-billed tropic bird"},
        {event_id:26,user_id:14,comment:"Dolphin, bottle-nose"},
        {event_id:30,user_id:2,comment:"Indian peacock"},
        {event_id:39,user_id:47,comment:"Gnu, brindled"},
        {event_id:32,user_id:25,comment:"Flamingo, roseat"},
        {event_id:3,user_id:33,comment:"Reindeer"},
        {event_id:50,user_id:12,comment:"Bee-eater, white-fronted"},
        {event_id:48,user_id:38,comment:"Crane, stanley"},
        {event_id:37,user_id:46,comment:"Richardson's ground squirrel"},
        {event_id:10,user_id:35,comment:"Phascogale, red-tailed"},
        {event_id:49,user_id:45,comment:"Water monitor"},
        {event_id:42,user_id:13,comment:"Cockatoo, red-tailed"},
        {event_id:20,user_id:41,comment:"Adouri (unidentified)"},
        {event_id:7,user_id:31,comment:"Pale white-eye"},
        {event_id:35,user_id:26,comment:"Shelduck, common"},
        {event_id:46,user_id:17,comment:"Orca"},
        {event_id:12,user_id:41,comment:"Brown pelican"},
        {event_id:12,user_id:7,comment:"Capybara"},
        {event_id:21,user_id:19,comment:"Sifaka, verreaux's"},
        {event_id:30,user_id:38,comment:"Cat, kaffir"},
        {event_id:48,user_id:34,comment:"Caracara, yellow-headed"},
        {event_id:15,user_id:18,comment:"Tortoise, burmese black mountain"},
        {event_id:50,user_id:33,comment:"Sable antelope"},
        {event_id:40,user_id:1,comment:"Eagle, bald"},
        {event_id:37,user_id:14,comment:"Tern, white-winged"},
        {event_id:26,user_id:16,comment:"Snake, green vine"},
        {event_id:3,user_id:4,comment:"Southern white-crowned shrike"},
        {event_id:20,user_id:5,comment:"Common turkey"},
        {event_id:6,user_id:4,comment:"Black-tailed prairie dog"},
        {event_id:25,user_id:9,comment:"Boa, columbian rainbow"},
        {event_id:38,user_id:49,comment:"Squirrel, smith's bush"},
        {event_id:45,user_id:13,comment:"Gull, pacific"},
        {event_id:23,user_id:4,comment:"Possum, golden brush-tailed"},
        {event_id:41,user_id:19,comment:"Brocket, brown"},
        {event_id:29,user_id:37,comment:"Greater blue-eared starling"},
        {event_id:47,user_id:28,comment:"Openbill, asian"}
      ]);
    });
};
